# Generated by Django 3.0.2 on 2020-01-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toilet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default=None, max_length=20)),
                ('street', models.CharField(default=None, max_length=50)),
                ('number', models.IntegerField(default=None)),
                ('reference', models.CharField(max_length=14)),
                ('price', models.IntegerField(default=None)),
                ('picture', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('clean', models.BooleanField(default=False)),
                ('accessible', models.BooleanField(default=False)),
            ],
        ),
    ]
