# Generated by Django 3.0.2 on 2020-01-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toilet',
            name='clean',
            field=models.CharField(max_length=20),
        ),
    ]
