# Generated by Django 3.0.2 on 2020-01-18 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toilets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toilet',
            name='accessible',
        ),
        migrations.RemoveField(
            model_name='toilet',
            name='clean',
        ),
    ]
