# Generated by Django 3.0.2 on 2020-01-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toilet',
            old_name='place',
            new_name='reference',
        ),
        migrations.AddField(
            model_name='toilet',
            name='city',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='toilet',
            name='country',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='toilet',
            name='number',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='toilet',
            name='street',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
