# Generated by Django 3.0.2 on 2020-01-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilets', '0002_auto_20200112_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='toilet',
            name='picture',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
