# Generated by Django 3.0.2 on 2020-01-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilets', '0002_auto_20200118_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='toilet',
            name='remarks',
            field=models.TextField(default='No remarks'),
        ),
    ]
