# Generated by Django 3.0.2 on 2020-01-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilets', '0003_toilet_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toilet',
            name='reference',
            field=models.CharField(max_length=20),
        ),
    ]
