# Generated by Django 3.0.2 on 2020-01-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilets', '0005_auto_20200116_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='toilet',
            name='accessible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='toilet',
            name='clean',
            field=models.BooleanField(default=False),
        ),
    ]
