# Generated by Django 3.0.2 on 2020-01-15 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toilets', '0005_auto_20200113_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toilet',
            name='country',
        ),
    ]
