# Generated by Django 3.0.2 on 2020-01-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilets', '0005_remove_toilet_clean'),
    ]

    operations = [
        migrations.AddField(
            model_name='toilet',
            name='clean',
            field=models.BooleanField(default=False),
        ),
    ]
