# Generated by Django 3.0.2 on 2020-01-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilets', '0006_remove_toilet_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='toilet',
            name='country',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
