# Generated by Django 3.0.2 on 2020-01-18 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toilets', '0006_toilet_clean'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toilet',
            name='clean',
        ),
    ]
