# Generated by Django 3.0.2 on 2020-01-15 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toilets', '0007_toilet_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toilet',
            name='country',
        ),
    ]
