# Generated by Django 3.0.2 on 2020-01-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilets', '0007_remove_toilet_clean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toilet',
            name='price',
            field=models.FloatField(),
        ),
    ]
