# Generated by Django 3.0.2 on 2020-01-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilets', '0008_auto_20200118_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toilet',
            name='price',
            field=models.FloatField(default=None),
        ),
    ]
