# Generated by Django 3.0.2 on 2020-01-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilets', '0009_auto_20200118_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toilet',
            name='reference',
            field=models.CharField(max_length=20),
        ),
    ]
