# Generated by Django 3.0.2 on 2020-01-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilets', '0010_auto_20200118_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toilet',
            name='city',
            field=models.CharField(choices=[('Antwerp', 'Antwerp'), ('Brussels', 'Brussels')], default='Antwerp', max_length=20),
        ),
    ]
