# Generated by Django 3.0.2 on 2020-01-19 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toilets', '0012_auto_20200119_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toilet',
            name='clean',
        ),
    ]
