# Generated by Django 3.0.2 on 2020-01-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilets', '0014_auto_20200119_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toilet',
            name='number',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
