# Generated by Django 3.0.2 on 2020-01-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilets', '0017_auto_20200119_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toilet',
            old_name='cleanliness',
            new_name='cleaned',
        ),
        migrations.AddField(
            model_name='toilet',
            name='wheelchair',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3),
        ),
    ]
