# Generated by Django 3.0.2 on 2020-01-19 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toilets', '0018_auto_20200119_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toilet',
            old_name='wheelchair',
            new_name='wheelchair_accessible',
        ),
    ]
