# Generated by Django 3.0.2 on 2020-01-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilets', '0020_remove_toilet_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toilet',
            name='cleaned',
            field=models.BooleanField(default=False),
        ),
    ]
