# Generated by Django 3.0.2 on 2020-01-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilets', '0021_auto_20200119_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toilet',
            name='cleaned',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3),
        ),
    ]
