# Generated by Django 3.0.2 on 2020-01-20 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toilets', '0022_auto_20200119_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toilet',
            name='reference',
        ),
    ]
