# Generated by Django 3.0.2 on 2020-01-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilets', '0023_remove_toilet_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toilet',
            name='city',
            field=models.CharField(choices=[('Antwerp', 'Antwerp'), ('Bruges', 'Bruges'), ('Brussels', 'Brussels'), ('Charleroi', 'Charleroi'), ('Ghent', 'Ghent'), ('Hasselt', 'Hasselt'), ('Kortrijk', 'Kortrijk'), ('Leuven', 'Leuven'), ('Liege', 'Liege'), ('Mechelen', 'Mechelen'), ('Mons', 'Mons'), ('Namur', 'Namur'), ('Nivelles', 'Nivelles'), ('Ostend', 'Ostend'), ('Tournai', 'Tournai')], default='Brussels', max_length=20),
        ),
    ]
