# Generated by Django 3.0.2 on 2020-01-22 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toilets', '0024_auto_20200122_0940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toilet',
            old_name='price',
            new_name='price_in_EUR',
        ),
    ]
